name: Update IPs4AMtunnel

on:
  schedule:
    - cron: '0 16 * * *'  # Runs at 16:00 UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete existing content
        run: |
          echo "" > ips-amtunnel.txt  # Clear the content of the file

      - name: Fetch content from URL
        run: |
          curl -s https://raw.githubusercontent.com/amclubs/am-cf-tunnel/main/ipv4.txt -o temp_ips.txt

      - name: Remove empty lines
        run: |
          # Delete any empty or whitespace-only lines
          sed -i '/^\s*$/d' temp_ips.txt

      - name: Process and save content
        run: |
          # Process the lines according to the specified rules
          awk '{
            if ($0 ~ /\.ns\.cloudflare\.com/) {
              print $0 "#NS.CL"
            } else if ($0 ~ /#/) {
              sub(/#.*/, "#AMTUN")
              print
            } else {
              print $0 "#AMTUN"
            }
          }' temp_ips.txt > ips-amtunnel.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ips-amtunnel.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update ips-amtunnel.txt with new content"
            git push
          else
            echo "No changes to commit."
          fi
