name: Fetch IPv4 onChange

on:
  schedule:
    - cron: '5 5,11,23 * * *'  # Runs every 6 hours (05:05, 11:05, 23:05 UTC)
  workflow_dispatch:

jobs:
  update_ipv4_collect:
    name: Update IPv4 Collection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # Updated from v2 → v4

      - name: Set up environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl

      - name: Fetch and extract IPv4 addresses
        id: fetch_ips
        shell: bash
        run: |
          # Define the URLs to monitor
          URL1="https://www.wetest.vip/page/cloudflare/address_v4.html"
          URL2="https://ip.164746.xyz/"

          # Fetch the current content of the pages
          CONTENT1=$(curl -s "$URL1")
          CONTENT2=$(curl -s "$URL2")

          # Extract IPv4 addresses using regex
          IP_ADDRESSES1=$(echo "$CONTENT1" | grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b')
          IP_ADDRESSES2=$(echo "$CONTENT2" | grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b')

          # Combine and remove duplicates
          ALL_IP_ADDRESSES=$(echo -e "$IP_ADDRESSES1\n$IP_ADDRESSES2" | awk '!seen[$0]++')

          # Replace ipv4collect.txt contents
          echo "$ALL_IP_ADDRESSES" > ipv4collect.txt

      - name: Append #IPV4Collect to lines without #
        shell: bash
        run: |
          awk '!/#/ { print $0 "#IPV4Collect" } /#/ { print }' ipv4collect.txt > temp.txt
          mv temp.txt ipv4collect.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5  # ✅ Modern, reliable commit action
        with:
          commit_message: "Update ipv4collect.txt with new IP addresses"
          file_pattern: ipv4collect.txt
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
