name: Proxy List Fetcher

on:
  schedule:
    - cron: "0 18 * * *"   # Runs every day at 18:00 UTC
  workflow_dispatch:        # Allow manual trigger

jobs:
  fetch_proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch and format proxy list
        run: |
          curl -s https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS.txt |
          grep -v '^Format:' |                                               # remove header line
          awk '{
            # Ensure the line has at least 4 fields (flag, ip:port, time, country)
            if (NF >= 4) {
              split($2, ipport, ":");
              if (ipport[1] ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && ipport[2] ~ /^[0-9]+$/) {
                print ipport[1] ":" ipport[2] "#" $4;
              }
            }
          }' | sort -u > opl.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add opl.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update opl.txt with latest proxy list"
            git push
          fi
          
